###
POST http://127.0.0.1:4000/users HTTP/1.1
content-type: application/json

{
    "email": "adam3@gmail.com",
    "username": "awdoimaw",
    "password": "aiowejfaowijef"
}

###
GET http://127.0.0.1:4000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUwYzUxZjhkLTc4ZDctNGM2Ni04MjEwLWQ5OTVmYTA1MjNhYiIsImlhdCI6MTY1NjAzMDcwOSwiZXhwIjoxNjU2MTE3MTA5fQ.-ZlzvUtULTa4XfHqFca--ytRjwUbpsZcWAsKcq_AukE

###
POST http://127.0.0.1:4000/users/login HTTP/1.1
content-type: application/json

{
    "email": "adam3@gmail.com",
    "password": "aiowejfaowijef"
}

###
POST http://127.0.0.1:4000/users/logout HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTYwMzAwNzIsImV4cCI6MTY1NjYzNDg3Mn0.BhMZMt5tPijCEmUVdXkWaILPFzrxzzJKaPLCSfFZ2H8"
}

###
POST http://127.0.0.1:4000/users/token HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTYwMzAwNzIsImV4cCI6MTY1NjYzNDg3Mn0.BhMZMt5tPijCEmUVdXkWaILPFzrxzzJKaPLCSfFZ2H8"
}
